stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  image: python:3.10
  script:
    - python -m unittest discover -s tests -p "*.py" -v | tee test_logs/unittest.log
  artifacts:
    paths:
      - unittest.log  # Speichert das Log als Artefakt
    expire_in: 1 week  # Optional: Log bleibt für 1 Woche gespeichert


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
