# For general information of how to configure prospector visit
# https://prospector.landscape.io/en/master/profiles.html

ignore-paths:
  - templates
  - build
  - docs

paths:
  - CorziliusNMR/

inherits:
  - strictness_high

pep257:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213
    - D415
    - D416



pylint:
  options:
    max-attributes: 25
    max-module-lines: 1500
    max-args: 15
    max-positional-arguments: 15
    max-locals: 25

pycodestyle:
  disable:
    - E203
    - W503
  enable:
    - W504

pyroma:
  run: true

bandit:
  run: true
