# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04  # 24.04 ist neu, 22.04 ist stabiler
  tools:
    python: "3.10"  # lieber eine LTS Version
  dir: docs

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt